apiVersion: v1
kind: Service
metadata:
  name: demo-security
  labels:
    app: demo-security
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: demo-security