apiVersion: v1
kind: Service
metadata:
  name: demo-security-springboot
  labels:
    app: demo-security-springboot
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8443
      targetPort: 443
  selector:
    app: demo-security-springboot
  type: LoadBalancer